In [25]:
import numpy as np
a = np.array([[1,2,3,4,5],[1,9,8,7,6]])
c= np.array([1,1,1,1,1])
# print(a)
list1 = np.array([1,2,3,4,5,6,7,8,9,10])
# list2 = np.array([11,12,13,14,15,16,17,18,19,20])
# print(list1+list2)
# print(list1.shape)
# print(list1.ndim)
# print(list1.dtype)
# print(list1.size)
print(a[0,0], a[1,4])
print(list1[0:4:])
print(np.sqrt(list1))


1 6
[1 2 3 4]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [26]:
# print(type(list1))


In [27]:
zerosArr= np.zeros((5,5))        #zeros(row,col)
print(zerosArr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
OnesArr = np.ones((2,6))
print(OnesArr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [29]:
Array = np.full((4,4),6)        #fill it with a fixed nym
print(Array)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [30]:
Identity = np.eye(6)      #identity matrix
print(Identity)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [31]:
arAnge= np.arange(5,50,5)       #arange(start,stop,step)     it stops before the num
print(arAnge)

[ 5 10 15 20 25 30 35 40 45]


In [32]:
linsp= np.linspace(0,1,5)       #بياخد اخر رقم معاه
print(linsp)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
randomizing = np.random.rand(3,3)               #float
randomizing_int = np.random.randint(1,6,(2,3))      #int only
randomizing_n = np.random.randn(1,6)
# random.seed

print(randomizing_n)


[[ 0.67909017 -0.65657337 -0.08867362  1.28776341  1.3236206  -2.09942729]]


In [34]:
b= np.arange(20)
print(b.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [35]:
flatt= np.array([0,1,2,3,4,5])
# b = flatt.flatten()
b = flatt.ravel()
print(b)

b[0]=100
print(flatt)
print(b)


trans = np.array([[1,2,3],[4,5,6]])
print((trans.T)*2+5)
trans[trans>3] +=5
print(trans)
print(np.subtract(trans,trans))

[0 1 2 3 4 5]
[100   1   2   3   4   5]
[100   1   2   3   4   5]
[[ 7 13]
 [ 9 15]
 [11 17]]
[[ 1  2  3]
 [ 9 10 11]]
[[0 0 0]
 [0 0 0]]


In [36]:
print(np.sqrt(list1))
print(list1.max())
print(a.sum())


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
10
46


Sum axis 0 for col and axis 1 for rows

In [37]:
print(a.mean(axis=0))
print(a.sum(axis=1))

[1.  5.5 5.5 5.5 5.5]
[15 31]


Broadcasting

In [55]:
a = np.array([[1,2,3,4,5],[1,9,8,7,6]])
c= np.array([1,1,1,1,1])
d = np.array([5,2,3,4,8])
# print(a+c)
print([a>5])
print(np.concatenate((c,d)))
print(np.vstack((c,d)))
print(np.hstack((c,d)))
print(np.split(d,5))

[array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])]
[1 1 1 1 1 5 2 3 4 8]
[[1 1 1 1 1]
 [5 2 3 4 8]]
[1 1 1 1 1 5 2 3 4 8]
[array([5]), array([2]), array([3]), array([4]), array([8])]


# conc is same as h stack
# copy vs view
# searching

In [64]:
f= c.copy()
f[0]=90
print(c)
print(f)
o= np.array([[1,2],[3,4]])
m=d.view()
m[0]=400
print(m)
print(d)

print(np.where(f==90))
print(np.any(f>4))
print(np.all(f%2==0))
for i in f:
    print(f)
print(np.linalg.det(o))


[1 1 1 1 1]
[90  1  1  1  1]
[400   2   3   4   8]
[400   2   3   4   8]
(array([0]),)
True
False
[90  1  1  1  1]
[90  1  1  1  1]
[90  1  1  1  1]
[90  1  1  1  1]
[90  1  1  1  1]
-2.0000000000000004


In [45]:
print(np.where(a>5), 1,0)
print(np.sort(a))
print(np.argsort(a))
print(np.sort(a)[::-1])

(array([1, 1, 1, 1]), array([1, 2, 3, 4])) 1 0
[[1 2 3 4 5]
 [1 6 7 8 9]]
[[0 1 2 3 4]
 [0 4 3 2 1]]
[[1 6 7 8 9]
 [1 2 3 4 5]]
